<?php
header("Content-Type: application/json");
error_reporting(0);
include 'db.php';
require('fpdf/fpdf.php');

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require 'phpmailer/PHPMailer.php';
require 'phpmailer/SMTP.php';
require 'phpmailer/Exception.php';

$user_id = $_GET['user_id'] ?? $_POST['user_id'] ?? null;

if (!$user_id) {
    echo json_encode(["status" => "error", "message" => "User ID required"]);
    exit;
}

// 1. Fetch User Profile
$stmt = $conn->prepare("SELECT name, email, phone, created_at FROM users WHERE id = ?");
$stmt->bind_param("i", $user_id);
$stmt->execute();
$user = $stmt->get_result()->fetch_assoc();

if (!$user) {
    echo json_encode(["status" => "error", "message" => "User not found"]);
    exit;
}

// 2. Fetch Dosha History
$dosha_data = [];
$stmt = $conn->prepare("SELECT checkin_date, vata_score, pitta_score, kapha_score FROM dosha_scores WHERE user_id = ? ORDER BY checkin_date DESC");
$stmt->bind_param("i", $user_id);
$stmt->execute();
$res = $stmt->get_result();
while ($row = $res->fetch_assoc()) {
    $dosha_data[] = $row;
}
$stmt->close();

// 3. Fetch Daily Check-ins (ALL columns)
$checkin_data = [];
$stmt = $conn->prepare("SELECT 
    DATE(created_at) as date,
    sleep_hours, sleep_quality, stress_level,
    morning_energy, evening_energy,
    body_dryness, body_heat, body_heaviness, cold_body,
    sweet_craving, spicy_craving,
    elimination, hydration_level, mood,
    physical_activity, digestion, appetite
    FROM daily_checkins WHERE user_id = ? ORDER BY created_at DESC");
$stmt->bind_param("i", $user_id);
$stmt->execute();
$res = $stmt->get_result();
while ($row = $res->fetch_assoc()) {
    $checkin_data[] = $row;
}
$stmt->close();


// 4. Generate PDF
class PDF extends FPDF
{
    function Header()
    {
        $this->SetFont('Arial','B',15);
        $this->Cell(0,10,'AyurPredict - User Data Export',0,1,'C');
        $this->Ln(5);
    }

    function Footer()
    {
        $this->SetY(-15);
        $this->SetFont('Arial','I',8);
        $this->Cell(0,10,'Page '.$this->PageNo().' - Generated by AyurPredict',0,0,'C');
    }
}

$pdf = new PDF('L', 'mm', 'A4'); // Landscape
$pdf->AddPage();
$pdf->SetFont('Arial','',12);

// Profile Section
$pdf->SetFont('Arial','B',14);
$pdf->Cell(0,10,'User Profile',0,1);
$pdf->SetFont('Arial','',12);
$pdf->Cell(40,10,'Name:',0,0); $pdf->Cell(0,10,$user['name'],0,1);
$pdf->Cell(40,10,'Email:',0,0); $pdf->Cell(0,10,$user['email'],0,1);
$pdf->Cell(40,10,'Phone:',0,0); $pdf->Cell(0,10,$user['phone'],0,1);
$pdf->Cell(40,10,'Joined:',0,0); $pdf->Cell(0,10,$user['created_at'],0,1);
$pdf->Ln(10);

// Dosha History Table
$pdf->SetFont('Arial','B',14);
$pdf->Cell(0,10,'Dosha History',0,1);
$pdf->SetFont('Arial','B',10);
$pdf->SetFillColor(200,220,255);
$pdf->Cell(40,8,'Date',1,0,'C',true);
$pdf->Cell(30,8,'Vata',1,0,'C',true);
$pdf->Cell(30,8,'Pitta',1,0,'C',true);
$pdf->Cell(30,8,'Kapha',1,1,'C',true);

$pdf->SetFont('Arial','',10);
foreach($dosha_data as $row) {
    $pdf->Cell(40,8,$row['checkin_date'],1);
    $pdf->Cell(30,8,$row['vata_score'],1);
    $pdf->Cell(30,8,$row['pitta_score'],1);
    $pdf->Cell(30,8,$row['kapha_score'],1,1);
}
$pdf->Ln(10);

// Daily Check-ins Table
$pdf->SetFont('Arial','B',14);
$pdf->Cell(0,10,'Daily Check-ins',0,1);

// Detailed Headers (Abbreviated to fit)
$headers = ['Date', 'Sleep', 'Qlty', 'Strss', 'M.En', 'E.En', 'Dry', 'Hot', 'Hvy', 'Cld', 'Swt', 'Spc', 'Elim', 'H2O', 'Mood', 'Actv', 'Digs', 'Appt'];
$widths =  [25,     12,      15,     15,      12,     12,     10,    10,    10,    10,    10,    10,    15,     12,    15,     15,     15,     15]; // Total ~240mm (A4 L is 297mm)

$pdf->SetFont('Arial','B',8);
$pdf->SetFillColor(200,255,200);
for($i=0; $i<count($headers); $i++) {
    $pdf->Cell($widths[$i], 8, $headers[$i], 1, 0, 'C', true);
}
$pdf->Ln();

$pdf->SetFont('Arial','',8);
foreach($checkin_data as $row) {
    $data = [
        $row['date'],
        $row['sleep_hours'], $row['sleep_quality'], $row['stress_level'],
        $row['morning_energy'], $row['evening_energy'],
        $row['body_dryness']?'Y':'N', $row['body_heat']?'Y':'N', $row['body_heaviness']?'Y':'N', $row['cold_body']?'Y':'N',
        $row['sweet_craving']?'Y':'N', $row['spicy_craving']?'Y':'N',
        $row['elimination'], $row['hydration_level'], $row['mood'],
        $row['physical_activity'], $row['digestion'], $row['appetite']
    ];
    
    // Check page break
    if($pdf->GetY() > 180) {
        $pdf->AddPage();
        // Re-print header
        $pdf->SetFont('Arial','B',8);
        for($i=0; $i<count($headers); $i++) {
            $pdf->Cell($widths[$i], 8, $headers[$i], 1, 0, 'C', true);
        }
        $pdf->Ln();
        $pdf->SetFont('Arial','',8);
    }

    for($i=0; $i<count($data); $i++) {
        // Truncate text if too long
        $text = $data[$i];
        if(strlen($text) > 8 && $i > 0) $text = substr($text, 0, 7) . '.'; 
        $pdf->Cell($widths[$i], 8, $text, 1, 0, 'C');
    }
    $pdf->Ln();
}

$pdf_content = $pdf->Output('S');

// 5. Send Email
$mail = new PHPMailer(true);

try {
    $mail->isSMTP();
    $mail->Host = 'smtp.gmail.com';
    $mail->SMTPAuth = true;
    $mail->Username = 'saimaniesward@gmail.com'; 
    $mail->Password = 'tmcm pmar ndny eybi';
    $mail->SMTPSecure = 'tls';
    $mail->Port = 587;

    $mail->setFrom('saimaniesward@gmail.com', 'AyurPredict Data Export');
    $mail->addAddress($user['email'], $user['name']);

    $mail->isHTML(true);
    $mail->Subject = 'Your AyurPredict Data Copy (PDF)';
    $mail->Body = "
        <h2>Hello {$user['name']},</h2>
        <p>Please find attached the PDF copy of your comprehensive personal data stored in AyurPredict.</p>
        <p>This document includes your Profile, complete Dosha History, and detailed Daily Check-in records.</p>
        <p>Regards,<br>AyurPredict Team</p>
    ";

    $mail->addStringAttachment($pdf_content, 'AyurPredict_Data.pdf');

    $mail->send();
    echo json_encode(["status" => "success", "message" => "PDF sent to " . $user['email']]);

} catch (Exception $e) {
    echo json_encode(["status" => "error", "message" => "Mailer Error: {$mail->ErrorInfo}"]);
}
?>
